# Generated by Django 4.1.3 on 2022-11-21 18:23

from django.db import migrations, models
import import_data.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=import_data.models.upload_data_formatter,
                    ),
                ),
            ],
        ),
    ]
